#!/bin/sh

hc() {
    herbstclient "$@"
}

tags() {
  seq 1 6
}

bind_keys() {
  local Mod=$1

  hc keyunbind --all

  hc keybind $Mod-Shift-q quit
  hc keybind $Mod-Shift-r reload
  hc keybind $Mod-Shift-c close
  hc keybind $Mod-Shift-Return spawn urxvtc
  hc keybind $Mod-p spawn dmenu_run

  hc keybind $Mod-h focus left
  hc keybind $Mod-j focus down
  hc keybind $Mod-k focus up
  hc keybind $Mod-l focus right
  hc keybind $Mod-Shift-h shift left
  hc keybind $Mod-Shift-j shift down
  hc keybind $Mod-Shift-k shift up
  hc keybind $Mod-Shift-l shift right

  hc keybind $Mod-u split bottom 0.5
  hc keybind $Mod-o split right 0.5
  hc keybind $Mod-Control-space split explode

  resizestep=0.05
  hc keybind $Mod-Control-h resize left +$resizestep
  hc keybind $Mod-Control-j resize down +$resizestep
  hc keybind $Mod-Control-k resize up +$resizestep
  hc keybind $Mod-Control-l resize right +$resizestep

  for i in $(tags) ; do
      hc keybind $Mod-$key use_index $i
      hc keybind $Mod-Shift-$key move_index $i
  done

  hc keybind $Mod-period use_index +1 --skip-visible
  hc keybind $Mod-comma  use_index -1 --skip-visible

  hc keybind $Mod-r remove
  hc keybind $Mod-space cycle_layout 1
  hc keybind $Mod-s floating toggle
  hc keybind $Mod-f fullscreen toggle
  hc keybind $Mod-p pseudotile toggle

  hc keybind $Mod-BackSpace   cycle_monitor
  hc keybind $Mod-Tab         cycle_all +1
  hc keybind $Mod-Shift-Tab   cycle_all -1
  hc keybind $Mod-c cycle
  hc keybind $Mod-i jumpto urgent

  hc mouseunbind --all
  hc mousebind $Mod-Button1 move
  hc mousebind $Mod-Button2 zoom
  hc mousebind $Mod-Button3 resize
}

set_theme() {
  hc set frame_border_active_color '#222222'
  hc set frame_border_normal_color '#101010'
  hc set frame_bg_normal_color '#565656'
  hc set frame_bg_active_color '#345F0C'
  hc set frame_border_width 1
  hc set window_border_width 3
  hc set window_border_inner_width 1
  hc set window_border_normal_color '#454545'
  hc set window_border_active_color '#9fbc00'
  hc set always_show_frame 1
  hc set frame_bg_transparent 1
  hc set frame_transparent_width 5
  hc set frame_gap 4
  # add overlapping window borders
  hc set window_gap -2
  hc set frame_padding 2
  hc set smart_window_surroundings 0
  hc set smart_frame_surroundings 1
  hc set mouse_recenter_gap 0
}

set_rules() {
  hc unrule -F
  hc rule focus=off
  hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
  hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
  hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
  hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
}

hc emit_hook reload

hc rename default 1 || true
for i in $(tags) ; do
    hc add $i
done

bind_keys Mod1

set_theme
set_rules

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# panel
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    $XDG_CONFIG_HOME/herbstluftwm/panel.sh $monitor &
done
