#!/bin/sh

. $(dirname $0)/style.sh

c() {
    herbstclient "$@"
}

keybind() {
  local M=Mod1

  c keyunbind --all

  c keybind $M-Shift-c close
  c keybind $M-Shift-q quit

  c keybind $M-h focus left
  c keybind $M-j focus down
  c keybind $M-k focus up
  c keybind $M-l focus right

  c keybind $M-Shift-h shift left
  c keybind $M-Shift-j shift down
  c keybind $M-Shift-k shift up
  c keybind $M-Shift-l shift right

  for i in $(seq 0 8); do
    c keybind $M-$(($i + 1)) focus_nth $i
  done

  c keybind $M-f fullscreen toggle
  c keybind $M-space pseudotile toggle

  c keybind $M-Shift-Return spawn urxvtc
  c keybind $M+p spawn dmenu_run -fn $FONT_BITMAP -nf $WHITE -nb $BLACK \
    -sf $GREEN -sb $BLACK -l 5 -p '>'

  c mouseunbind --all
  c mousebind $M-Button1 move
  c mousebind $M-Button2 zoom
  c mousebind $M-Button3 resize
}

style() {
  c set frame_border_width 4
  c set frame_gap 6
  c set frame_padding 0
  c set frame_bg_transparent 1
  c set frame_transparent_width 2
  c set frame_border_width 0
  c set frame_bg_active_color $MEDIUM
  c set frame_bg_normal_color $DARK
  c set always_show_frame 1
  c set smart_frame_surroundings 0

  c set smart_window_surroundings 0
  c set window_gap 0
  c set window_border_width 2
  c set window_border_active_color $LIGHT
  c set window_border_normal_color $DARK
  c set window_border_urgent_color $RED
}

rule() {
  c unrule -F
  c rule focus=on
  c rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' \
    pseudotile=on
  c rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
  c rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' \
    manage=off
}

spawn_wait() {
  c spawn "$@"
  sleep 0.1s
}

layout() {
  c load '
    (split horizontal:0.600000:0
      (clients vertical:0)
      (split vertical:0.800000:0
        (clients vertical:0) (clients vertical:0)))'

  spawn_wait urxvtc
  c set_layout max

  c focus right
  spawn_wait urxvtc
  c set_layout max

  c focus down
  spawn_wait urxvtc
  c set_layout max

  c focus up
  c focus left
}

c emit_hook reload

keybind
style
rule
layout

c unlock
