#!/bin/sh

MONITOR=$1
FONT="$2"
FONT_WIDTH=8

WHITE='#fdfaf6'
GREY='#93a1a1'
BLACK='#657b83'

RED='#dc322f'
ORANGE='#cb4b16'
YELLOW='#b58900'
GREEN='#859900'

NOR_BG=$WHITE
NOR_FG=$BLACK
SEL_BG=$GREEN
SEL_FG=$WHITE
URG_BG=$RED
URG_FG=$WHITE
SEP_FG=$GREY
EMP_FG=$GREY
WIN_FG=$GREY

BAT_BG=$GREY
BAT_LO=$RED
BAT_ME=$ORANGE
BAT_HI=$YELLOW
BAT_FU=$GREEN

geometry() {
  herbstclient monitor_rect "$MONITOR" | awk "{ print \$$1 }"
}

GAP=6
X=$(($(geometry 1) + $GAP))
Y=$(($(geometry 2) + $GAP))
WIDTH=$(($(geometry 3) - ($GAP*2)))
HEIGHT=21

herbstclient pad $MONITOR $(($HEIGHT + $GAP))

TAGS=
update_tags() {
  TAGS="$(herbstclient tag_status $MONITOR)"
}

TITLE=
update_title() {
  TITLE="$(printf '%s' "$1" | sed 's/.*\t//;s/\^/\^\^/g')"
}

DATE=
update_date() {
  DATE="$(printf '%s' "$1" | sed 's/^date\t//')"
}

BATTERY_WIDTH=60
BATTERY_SYS=/sys/class/power_supply/BAT0
[ -d $BATTERY_SYS ] || BATTERY_WIDTH=0

BATTERY=0
update_battery() {
  BATTERY="$(printf '%s' "$1" | sed 's/^battery\t//')"
}

plain_width() {
  local str
  str=$(printf '%s' "$1" | sed 's/\^[^(]*([^)]*)//g')
  printf '%d' $((${#str} * $FONT_WIDTH))
}

battery_color() {
  local c=$BAT_FU

  [ "$BATTERY" -lt 75 ] && c=$BAT_HI
  [ "$BATTERY" -lt 50 ] && c=$BAT_ME
  [ "$BATTERY" -lt 25 ] && c=$BAT_LO

  printf '%s' $c
}

format() {
  local sep="^bg()^fg($SEP_FG) | "
  local right="$sep^fg($SEP_FG)${DATE% *} ^fg($NOR_FG)${DATE#* }"
  local tagbg
  local tagfg

  for i in $TAGS; do
    tagbg=""
    tagfg=""
    case $i in
      '#'*)
        tagbg=$SEL_BG
        tagfg=$SEL_FG
        ;;
      ':'*)
        tagfg=$NOR_FG
        ;;
      '!'*)
        tagbg=$URG_BG
        tagfg=$URG_FG
        ;;
      *)
        tagfg=$EMP_FG
        ;;
    esac
    printf '^bg(%s)^fg(%s) %s ' "$tagbg" "$tagfg" "${i#?}"
  done

  printf '%s^bg()^fg(%s) %s' "$sep" $WIN_FG "$TITLE"
  printf '^pa(%d)' $(($WIDTH - $(plain_width "$right") - 10 - $BATTERY_WIDTH))
  [ $BATTERY_WIDTH -eq 0 ] || printf '%d' $BATTERY |
    gdbar -fg $(battery_color $SEL_BG) \
          -bg $BAT_BG \
          -w $BATTERY_WIDTH \
          -s o \
          -nonl
  printf '%s\n' "$right"
}

{

  (
    pdate=
    pbat=
    while true; do
      sleep 1 || break

      ndate="$(date +'%Y-%m-%d %H:%M')"
      [ "$pdate" = "$ndate" ] || {
        printf 'date\t%s\n' "$ndate"
        pdate="$ndate"
      }

      [ $BATTERY_WIDTH -eq 0 ] && continue

      enow=$(cat $BATTERY_SYS/energy_now)
      efull=$(cat $BATTERY_SYS/energy_full)
      nbat=$(expr \( 100 \* $enow \) / $efull)
      [ "$pbat" -eq "$nbat" ] || {
        printf 'battery\t%d\n' "$nbat"
        pbat="$nbat"
      }
    done
  ) &
  chld=$!

  herbstclient --idle

  kill $chld

} 2> /dev/null | {

  update_tags
  format

  while true; do
    IFS=$(printf '\n') read -r hook || break

    case "$hook" in
      tag*)
        update_tags
        ;;
      focus_changed*|window_title_changed*)
        update_title "$hook"
        ;;
      quit_panel*|reload*)
        exit
        ;;
      date*)
        update_date "$hook"
        ;;
      battery*)
        update_battery "$hook"
        ;;
    esac

    format
  done

} 2> /dev/null | dzen2 \
  -ta l \
  -fn "$FONT" \
  -w $WIDTH \
  -h $HEIGHT \
  -x $X \
  -y $Y \
  -bg $NOR_BG \
  -fg $NOR_FG \
  -e 'button3='
