#!/bin/sh

FONT='DejaVu Sans'
SIZE=10
HEIGHT=16
MARGIN=4
FG='#657b83'
BG='#eee8d5'
_IFS=$IFS

bspc desktop ^1 -n 1
bspc monitor -a 2 3 4 5 6

bspc rule -a MPlayer --floating
bspc rule -a mpv --floating
bspc rule -a Gimp --floating

bspc config top_padding $(expr $HEIGHT + $MARGIN)
bspc config border_width 1
bspc config window_gap 4
bspc config focused_border_color "#d0ccc0"
bspc config normal_border_color "#fdfaf6"

cat ~/.panel-fifo | (
  while read -r line; do
    info=''
    case $line in
      W*)
        IFS=':'
        set -- ${line#?}
        while [ $# -gt 0 ]; do
          item=$1
          name=${item#?}
          case $item in
              [FO]*)
                  # focused desktop
                  info="$info^bg(#fdfaf6) $name ^bg() "
                  ;;
              [Uu]*)
                  # urgent desktop
                  info="$info^fg(#dc322f) $name ^fg() "
                  ;;
              o*)
                  # occupied desktop
                  info="$info $name  "
                  ;;
            esac
          shift
        done
        IFS=$_IFS
        ;;
    esac
    printf '%s\n' "$info"
  done
) | dzen2 -y $MARGIN -x $MARGIN -h $HEIGHT -ta l -dock -fn "$FONT:size=$SIZE" -fg $FG -bg $BG &
