#!/usr/bin/env bash

HEIGHT=16

bspc desktop ^1 -n 1
bspc monitor -a 2 3 4 5 6

bspc rule -a MPlayer --floating
bspc rule -a mpv --floating
bspc rule -a Gimp --floating

bspc config top_padding $HEIGHT
bspc config border_width 1
bspc config window_gap 4
bspc config focused_border_color "#d0ccc0"
bspc config normal_border_color "#fdfaf6"

$(readlink -f $(dirname $0))/bspwmbar &
