#!/bin/sh

. $(dirname $0)/config

mkdir -p $BSPWM_CACHE

sxhkd &

[ -e $PANEL_FIFO ] && rm $PANEL_FIFO
mkfifo $PANEL_FIFO

$(dirname $0)/panel &

$(dirname $0)/poller > $PANEL_FIFO &
bspc control --subscribe > $PANEL_FIFO &
xtitle -sf 'T%s' > $PANEL_FIFO &

exec bspwm
