#!/bin/sh

. $(dirname $0)/config

colorize() {
  local s="$1"
  local fg bg ul
  eval fg=\$COLOR_${2}_FG
  eval bg=\$COLOR_${2}_BG
  [ $# -eq 3 ] && eval ul=\$COLOR_${2}_UL

  if [ "$ul" ]; then
    printf -- '%%{F%s}%%{B%s}%%{U%s}%%{+u}%s%%{-u}%%{U-}%%{F-}%%{B-}' $fg $bg $ul "$s"
  else
    printf -- '%%{F%s}%%{B%s}%s%%{F-}%%{B-}' $fg $bg "$s"
  fi
}

bspwm_parse() {
  local oifs="$IFS"

  IFS=:
  for d in $1; do
    case $d in
      O*)
        printf -- '%s' "$(colorize " ${d#?} " OCCUPIED_FOCUSED 1)"
        ;;
      F*)
        printf -- '%s' "$(colorize " ${d#?} " FREE_FOCUSED 1)"
        ;;
      U*|u*)
        printf -- '%s' "$(colorize " ${d#?} " URGENT)"
        ;;
      o*)
        printf -- '%s' "$(colorize " ${d#?} " OCCUPIED)"
        ;;
      f*)
        printf -- '%s' "$(colorize " ${d#?} " FREE)"
        ;;
    esac
  done

  IFS="$oifs"
}

battery_color() {
  local c=BATTERY_FULL

  [ "$1" -lt 75 ] && c=BATTERY_HIGH
  [ "$1" -lt 50 ] && c=BATTERY_MEDIUM
  [ "$1" -lt 25 ] && c=BATTERY_LOW

  printf '%s' $c
}

battery_parse() {
  local bat=
  local ac=
  local oifs="$IFS"
  local percentage="$(colorize '%%' BATTERY_PERCENTAGE)"

  IFS=:
  for b in $1; do
    case $b in
      B*)
        bat="$bat $(colorize " ${b#?}" $(battery_color ${b#?}))$percentage"
        ;;
      A*)
        [ "${b#?}" = 0 ] || ac="$(colorize AC BATTERY_AC)"
    esac
  done
  printf -- '%s%s' "$ac" "$bat"

  IFS="$oifs"
}

parse() {
  local desktops title system dt bat

  while read -r line; do
    title=bspwm

    case $line in
      W*)
        desktops=$(bspwm_parse ${line#?})
        ;;
      D*)
        dt="$(colorize " ${line#?} " DATE)"
        ;;
      B*)
        bat="$(battery_parse "${line#?}")"
        ;;
    esac

    printf -- '%s\n' "%{l}${desktops}%{c}${title}%{r}$bat $dt"
  done
}

cat $PANEL_FIFO | parse | bar \
  -f "$FONT" \
  -g ${PANEL_WIDTH}x$PANEL_HEIGHT+$PANEL_X+$PANEL_Y \
  -F $COLOR_FG \
  -B $COLOR_BG \
  -u $PANEL_UL

wait
